version: '2'
services:
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: connection
      MYSQL_USER: manish
      MYSQL_PASSWORD: Test123456
      MYSQL_ROOT_PASSWORD: Test123456
    ports:
      - "3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - net

  www:
    container_name: web
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./crud:/var/www/html/
        #      - ./php:/usr/local/etc/php 
    links:
      - db
    networks:
      - net

networks:
  net:
